### ISSUE TITLE
Headless daemons should be configured exclusively through config file

### ISSUE THREAD

**Issue by Badg** [Muterra/py_hypergolix#14]
Currently, you configure a headless daemon (ie the CLI daemon, so, at the moment, every daemon) primarily through the ```hypergolix config``` command. This command should be deprecated, in favor of the following:

1. When it finally exists, the GUI app should configure through the gui. It can still use the same config file so store stuff, though.
2. Daemons will always exist, for example to use remotely on a Raspberry Pi. They should always be configured directly through the config file itself; it's faster, cleaner to do, just as easy via terminal/SSH, can be automatically remotely loaded, etc.
3. Servers should also be configured through the same config file

Specific requirements to do this:

- [x] Improve the config file format (#15)
- [x] Expand config flexibility, so it can be used for servers (#16)
- [x] Add deprecation warnings to the config CLI (6cfd7fa)
- [x] Support better config file location (check ENV, several directories, etc) (#17)
- [x] Document changes (#21; see Muterra/doc-hypergolix@23f2cd0)
