### ISSUE TITLE
Hypergolix GUI roadmap

### ISSUE THREAD

**Issue by Badg** [Muterra/py_hypergolix#20]
This issue is going to expand as features get added to the GUI roadmap. At the moment it is definitely **not** all-inclusive.

Hypergolix should have three different "flavors":

1. A "headless" app daemon, to run on ex. a Raspberry Pi, which is wholly configured via a config file, and supports administration from a different account (intended to be used as an autonomous or semi-autonomous device), but is otherwise unavailable for interactive use (dynamic config, dynamic error reporting, etc)  
    - [x] Daemonization
    - [ ] Config file (see #14 )
    - [ ] Daemonization privilege de-escalation, required for autonomous login on startup (use sudo to start, only give root access to config file, config file contains master secret = no password necessary)
    - [ ] Special "administrator" contact in Rolodex
    - [ ] Hypergolix-enabled logging facility
    - [ ] Logging facility sharability with administrator  

    Note: until implemented, this list should be updated whenever new features are added to Hypergolix
2. A "headless" server daemon, configured via same file as above, probably just as a subset of the app daemon  
    - [x] Daemonization
    - [ ] Config file (see #16 )
3. A GUI app, for **all** interactive use.  
    - [ ] Config through GUI, stored in same config file
    - [ ] Notifications for ex. errors, connection problems w/ remotes, etc
    - [ ] Ability to be launched at startup
    - [ ] System tray minimization
    - [ ] Ability to remote administer headless daemons
